load(":define_modules.bzl", "define_modules")
load("//build/kernel/kleaf:kernel.bzl", "ddk_headers")

define_modules("sdxkova", "perf")
define_modules("sdxkova", "debug")

define_modules("sdxkova.cpe.wkk", "perf")
define_modules("sdxkova.cpe.wkk", "debug")

define_modules("sdxkova.512", "perf")
define_modules("sdxkova.512", "debug")

define_modules("sdxkova.cpe.tarang", "perf")
define_modules("sdxkova.cpe.tarang", "debug")

define_modules("sdxkova.prpl", "perf")
define_modules("sdxkova.prpl", "debug")

define_modules("taycan", "perf")
define_modules("taycan", "debug")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

ddk_headers(
    name = "include_headers",
    hdrs = glob([
        "drivers/platform/msm/include/linux/*.h",
        "drivers/platform/msm/include/uapi/linux/*.h",
    ]),
    includes = [
        "drivers/platform/msm/include",
        "drivers/platform/msm/include/linux",
        "drivers/platform/msm/include/uapi",
    ],
)

ddk_headers(
    name = "gsi_headers",
    hdrs = glob([
        "drivers/platform/msm/gsi/*.h",
        "drivers/platform/msm/gsi/gsihal/*.h",
    ]),
    includes = [
        "drivers/platform/msm/gsi",
        "drivers/platform/msm/gsi/gsihal",
    ],
)

ddk_headers(
    name = "ipa_headers",
    hdrs = glob([
        "drivers/platform/msm/ipa/*.h",
        "drivers/platform/msm/ipa/ipa_test_module/*.h",
        "drivers/platform/msm/ipa/ipa_v3/*.h",
        "drivers/platform/msm/ipa/ipa_v3/ipahal/*.h",
    ]),
    includes = [
        "drivers/platform/msm/ipa",
        "drivers/platform/msm/ipa/ipa_test_module",
        "drivers/platform/msm/ipa/ipa_v3",
        "drivers/platform/msm/ipa/ipa_v3/ipahal",
    ],
)

ddk_headers(
    name = "ipa_clients",
    hdrs = glob([
        "drivers/platform/msm/ipa/ipa_clients/*.h",
    ]),
    includes = ["drivers/platform/msm/ipa/ipa_clients"],
)

ddk_headers(
    name = "debug_config_headers",
    hdrs = [
        "config/dataipa_debug.h",
        "config/dataipa.h",
    ],
    includes = ["config"],
)

ddk_headers(
    name = "perf_config_headers",
    hdrs = [
        "config/dataipa.h",
    ],
    includes = ["config"],
)

genrule(
    name = "debug_defconfig",
    srcs = [
        "config/dataipa_debug.conf",
        "config/dataipa_QGKI.conf",
    ],
    outs = ["debug_defconfig.conf"],
    cmd = "cat $(SRCS) | sed -e 's/^export //g' > $@",
)

genrule(
    name = "perf_defconfig",
    srcs = [
        "config/dataipa_QGKI.conf",
    ],
    outs = ["perf_defconfig.conf"],
    cmd = "cat $(SRCS) | sed -e 's/^export //g' > $@",
)

genrule(
    name = "ipsec_debug_defconfig",
    srcs = [
        "config/dataipa_debug.conf",
        "config/dataipa_QGKI.conf",
        "config/dataipa_ipsec.conf",
    ],
    outs = ["ipsec_debug_defconfig.conf"],
    cmd = "cat $(SRCS) | sed -e 's/^export //g' > $@",
)

genrule(
    name = "ipsec_perf_defconfig",
    srcs = [
        "config/dataipa_QGKI.conf",
        "config/dataipa_ipsec.conf",
    ],
    outs = ["ipsec_perf_defconfig.conf"],
    cmd = "cat $(SRCS) | sed -e 's/^export //g' > $@",
)
