# SPDX-License-Identifier: GPL-2.0-only
ifeq ($(origin DATAIPADRVTOP),undefined)
$(warning DATAIPADRVTOP is not set)
else
$(warning DATAIPADRVTOP is set to: $(DATAIPADRVTOP))
endif

#MSMs - GKI
ifeq ($(filter $(CONFIG_ARCH_LAHAINA) $(CONFIG_ARCH_HOLI), y),y)
LINUXINCLUDE    += -include $(srctree)/techpack/dataipa/config/dataipa.h
ifeq ($(CONFIG_QGKI),y)
include $(srctree)/techpack/dataipa/config/dataipa_QGKI.conf
ifeq ($(CONFIG_LOCALVERSION), "-qgki-debug")
include $(srctree)/techpack/dataipa/config/dataipa_debug.conf
LINUXINCLUDE    += -include $(srctree)/techpack/dataipa/config/dataipa_debug.h
endif
else
include $(srctree)/techpack/dataipa/config/dataipa_GKI.conf
endif
endif


#MSM - Vendor SI
ifeq ($(CONFIG_ARCH_PARROT), y)
DATAIPADRVTOP = $(srctree)/../../vendor/qcom/opensource/dataipa/drivers/platform/msm
LINUXINCLUDE    += -include $(srctree)/../../vendor/qcom/opensource/dataipa/config/dataipa_vendor.h
include $(srctree)/../../vendor/qcom/opensource/dataipa/config/dataipa_GKI.conf
ifeq ($(CONFIG_LOCALVERSION), "-gki-consolidate")
include $(srctree)/../../vendor/qcom/opensource/dataipa/config/dataipa_debug.conf
LINUXINCLUDE    += -include $(srctree)/../../vendor/qcom/opensource/dataipa/config/dataipa_debug.h
endif
endif



#MSM - Vendor SI
ifeq ($(CONFIG_ARCH_WAIPIO), y)
DATAIPADRVTOP = $(srctree)/../../vendor/qcom/opensource/dataipa/drivers/platform/msm
LINUXINCLUDE    += -include $(srctree)/../../vendor/qcom/opensource/dataipa/config/dataipa_vendor.h
include $(srctree)/../../vendor/qcom/opensource/dataipa/config/dataipa_GKI.conf
ifeq ($(CONFIG_LOCALVERSION), "-gki-consolidate")
include $(srctree)/../../vendor/qcom/opensource/dataipa/config/dataipa_GKI_consolidate.conf
LINUXINCLUDE    += -include $(srctree)/../../vendor/qcom/opensource/dataipa/config/dataipa_debug.h
endif
endif

ifeq ($(CONFIG_ARCH_KALAMA), y)
DATAIPADRVTOP = $(srctree)/../../vendor/qcom/opensource/dataipa/drivers/platform/msm
LINUXINCLUDE    += -include $(srctree)/../../vendor/qcom/opensource/dataipa/config/dataipa_vendor.h
include $(srctree)/../../vendor/qcom/opensource/dataipa/config/dataipa_GKI.conf
ifeq ($(CONFIG_LOCALVERSION), "-gki-consolidate")
include $(srctree)/../../vendor/qcom/opensource/dataipa/config/dataipa_GKI_consolidate.conf
LINUXINCLUDE    += -include $(srctree)/../../vendor/qcom/opensource/dataipa/config/dataipa_debug.h
endif
endif

ifeq ($(CONFIG_ARCH_KHAJE), y)
DATAIPADRVTOP = $(srctree)/../../vendor/qcom/opensource/dataipa/drivers/platform/msm
LINUXINCLUDE    += -include $(srctree)/../../vendor/qcom/opensource/dataipa/config/dataipa_vendor_ipav4.h
include $(srctree)/../../vendor/qcom/opensource/dataipa/config/dataipa_GKI_ipav4.conf
ifeq ($(CONFIG_LOCALVERSION), "-gki-consolidate")
include $(srctree)/../../vendor/qcom/opensource/dataipa/config/dataipa_GKI_consolidate.conf
LINUXINCLUDE    += -include $(srctree)/../../vendor/qcom/opensource/dataipa/config/dataipa_debug.h
endif
endif

#MDMs
ifeq ($(CONFIG_ARCH_SDXLEMUR), y)
LINUXINCLUDE    += -include $(srctree)/techpack/dataipa/config/dataipa.h
include $(srctree)/techpack/dataipa/config/dataipa_QGKI.conf
ifneq ($(CONFIG_LOCALVERSION), "-perf")
include $(srctree)/techpack/dataipa/config/dataipa_debug.conf
LINUXINCLUDE    += -include $(srctree)/techpack/dataipa/config/dataipa_debug.h
endif
endif

ifeq ($(CONFIG_ARCH_SDXNIGHTJAR), y)
LINUXINCLUDE    += -include $(srctree)/techpack/dataipa/config/sdx12dataipa.h
include $(srctree)/techpack/dataipa/config/sdx12dataipa_QGKI.conf
ifneq ($(CONFIG_LOCALVERSION), "-perf")
include $(srctree)/techpack/dataipa/config/dataipa_debug.conf
LINUXINCLUDE    += -include $(srctree)/techpack/dataipa/config/dataipa_debug.h
endif
endif

ifeq ($(CONFIG_ARCH_SCUBA), y)
LINUXINCLUDE    += -include $(srctree)/techpack/dataipa/config/auto_dataipa.h
include $(srctree)/techpack/dataipa/config/auto_dataipa_QGKI.conf
ifneq ($(CONFIG_LOCALVERSION), "-perf")
include $(srctree)/techpack/dataipa/config/dataipa_debug.conf
LINUXINCLUDE    += -include $(srctree)/techpack/dataipa/config/dataipa_debug.h
endif
endif

ifeq ($(CONFIG_ARCH_SA410M), y)
DATAIPADRVTOP = $(srctree)/../../../dataipa/drivers/platform/msm
LINUXINCLUDE    += -include $(srctree)/../../../dataipa/config/auto_dataipa.h
include $(srctree)/../../../dataipa/config/auto_dataipa_QGKI.conf
ifneq ($(CONFIG_LOCALVERSION), "-perf")
include $(srctree)/../../../dataipa/config/dataipa_debug.conf
LINUXINCLUDE    += -include $(srctree)/../../../dataipa/config/dataipa_debug.h
endif
endif

ifeq ($(CONFIG_ARCH_SA515M), y)
LINUXINCLUDE    += -include $(srctree)/techpack/dataipa/config/auto_dataipa.h
include $(srctree)/techpack/dataipa/config/auto_dataipa_QGKI.conf
ifneq ($(CONFIG_LOCALVERSION), "-perf")
include $(srctree)/techpack/dataipa/config/dataipa_debug.conf
LINUXINCLUDE    += -include $(srctree)/techpack/dataipa/config/dataipa_debug.h
endif
endif

ifeq ($(CONFIG_ARCH_KHAJE), y)
LINUXINCLUDE    += -include $(srctree)/techpack/dataipa/config/dataipa.h
include $(srctree)/techpack/dataipa/config/dataipa_QGKI.conf
ifneq ($(CONFIG_LOCALVERSION), "-perf")
include $(srctree)/techpack/dataipa/config/dataipa_debug.conf
LINUXINCLUDE    += -include $(srctree)/techpack/dataipa/config/dataipa_debug.h
endif
endif

ifeq ($(CONFIG_ARCH_SDXBAAGHA), y)
DATAIPADRVTOP = $(MODULE_OUT)/drivers/platform/msm
LINUXINCLUDE    += -include $(MODULE_OUT)/config/dataipa_hw5_0.h
include $(MODULE_OUT)/config/dataipa_hw5_0_QGKI.conf
ifneq ($(CONFIG_LOCALVERSION), "-perf")
include $(MODULE_OUT)/config/dataipa_debug.conf
LINUXINCLUDE    += -include $(MODULE_OUT)/config/dataipa_debug.h
endif
endif

ifeq ($(filter $(CONFIG_ARCH_SDXPINN) $(CONFIG_ARCH_SDXKOVA), y), y)
ifeq ($(origin DATAIPADRVTOP),undefined)
$(warning DATAIPADRVTOP is not set)
DATAIPADRVTOP = $(srctree)/../../../dataipa/drivers/platform/msm
LINUXINCLUDE    += -include $(srctree)/../../../dataipa/config/dataipa.h
include $(srctree)/../../../dataipa/config/dataipa_QGKI.conf
ifneq ($(CONFIG_LOCALVERSION), "-perf")
include $(srctree)/../../../dataipa/config/dataipa_debug.conf
LINUXINCLUDE    += -include $(srctree)/../../../dataipa/config/dataipa_debug.h
endif
else
$(warning DATAIPADRVTOP is set to: $(DATAIPADRVTOP))
LINUXINCLUDE    += -include $(DATAIPADRVTOP)/../../../config/dataipa.h
include $(DATAIPADRVTOP)/../../../config/dataipa_QGKI.conf
ifneq ($(CONFIG_LOCALVERSION), "-perf")
include $(DATAIPADRVTOP)/../../../config/dataipa_debug.conf
LINUXINCLUDE    += -include $(DATAIPADRVTOP)/../../../config/dataipa_debug.h
endif
endif
endif

#Amboseli/SA535
ifeq ($(filter $(CONFIG_ARCH_QCOM), y), y)
ifeq ($(origin DATAIPADRVTOP),undefined)
$(warning DATAIPADRVTOP is not set)
DATAIPADRVTOP = $(srctree)/../../../dataipa/drivers/platform/msm
LINUXINCLUDE += -include $(srctree)/../../../dataipa/config/dataipa_hw7_0.h
include $(srctree)/../../../dataipa/config/dataipa_hw7_0_QGKI.conf
ifneq ($(CONFIG_LOCALVERSION), "-perf")
include $(srctree)/../../../dataipa/config/dataipa_debug.conf
LINUXINCLUDE += -include $(srctree)/../../../dataipa/config/dataipa_debug.h
endif
else
$(warning DATAIPADRVTOP is set to: $(DATAIPADRVTOP))
LINUXINCLUDE += -include $(DATAIPADRVTOP)/../../../config/dataipa_hw7_0.h
include $(DATAIPADRVTOP)/../../../config/dataipa_hw7_0_QGKI.conf
ifneq ($(CONFIG_LOCALVERSION), "-perf")
include $(DATAIPADRVTOP)/../../../config/dataipa_debug.conf
LINUXINCLUDE += -include $(DATAIPADRVTOP)/../../../config/dataipa_debug.h
endif
endif
endif

ifneq (,$(filter $(CONFIG_IPA3) $(CONFIG_GSI),y m))
LINUXINCLUDE += -I$(DATAIPADRVTOP)/include
LINUXINCLUDE += -I$(DATAIPADRVTOP)/include/linux
LINUXINCLUDE += -I$(DATAIPADRVTOP)/include/uapi
LINUXINCLUDE += -I$(DATAIPADRVTOP)/gsi
LINUXINCLUDE += -I$(DATAIPADRVTOP)/gsi/gsihal
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_v3
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_v3/ipahal
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_clients
LINUXINCLUDE += -I$(DATAIPADRVTOP)/../../../exports/
ifneq (,$(filter $(CONFIG_IPA_KERNEL_TESTS_MODULE),y m))
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_test_module
endif
endif

ifneq (,$(filter $(CONFIG_IPA3_REGDUMP),y m))
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_v3/dump
endif

ifneq (,$(filter $(CONFIG_IPA3_REGDUMP_IPA_4_5),y m))
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_v3/dump/ipa4.5
endif

ifneq (,$(filter $(CONFIG_IPA3_REGDUMP_IPA_5_0),y m))
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_v3/dump/ipa5.0
endif

ifneq (,$(filter $(CONFIG_IPA3_REGDUMP_IPA_5_5),y m))
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_v3/dump/ipa5.5
endif

ifneq (,$(filter $(CONFIG_IPA3_REGDUMP_IPA_6_0),y m))
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_v3/dump/ipa6.0
endif

ifneq (,$(filter $(CONFIG_IPA3_REGDUMP_IPA_7_0),y m))
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_v3/dump/ipa7.0
endif


obj-$(CONFIG_GSI) += gsi/
obj-$(CONFIG_IPA3) += ipa/
